{ { - if .Values.serviceAccount.create - } }
apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "goatherdmapper.serviceAccountName" . } }
  labels:
  { { - include "goatherdmapper.labels" . | nindent 4 } }
  { { - with .Values.serviceAccount.annotations } }
  annotations:
  { { - toYaml . | nindent 4 } }
  { { - end } }
  { { - end } }
