//  protoc --go_out=. --go_opt=paths=source_relative  --go-grpc_out=. --go-grpc_opt=paths=source_relative  comm/packetsummary.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: comm/packetsummary.proto

package comm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main PacketSummary protobuf
type PacketSummaryMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CapID  uint32 `protobuf:"varint,1,opt,name=CapID,proto3" json:"CapID,omitempty"` // registered CapturePoint ID this packetsummary originates from
	SrcIP  uint32 `protobuf:"varint,2,opt,name=SrcIP,proto3" json:"SrcIP,omitempty"`
	SrcMac uint32 `protobuf:"varint,3,opt,name=SrcMac,proto3" json:"SrcMac,omitempty"`
	DstIP  uint32 `protobuf:"varint,4,opt,name=DstIP,proto3" json:"DstIP,omitempty"`
	DstMac uint32 `protobuf:"varint,5,opt,name=DstMac,proto3" json:"DstMac,omitempty"`
	TTL    uint32 `protobuf:"varint,6,opt,name=TTL,proto3" json:"TTL,omitempty"`
}

func (x *PacketSummaryMessage) Reset() {
	*x = PacketSummaryMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_packetsummary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketSummaryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketSummaryMessage) ProtoMessage() {}

func (x *PacketSummaryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_packetsummary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketSummaryMessage.ProtoReflect.Descriptor instead.
func (*PacketSummaryMessage) Descriptor() ([]byte, []int) {
	return file_packets_packetsummary_proto_rawDescGZIP(), []int{0}
}

func (x *PacketSummaryMessage) GetCapID() uint32 {
	if x != nil {
		return x.CapID
	}
	return 0
}

func (x *PacketSummaryMessage) GetSrcIP() uint32 {
	if x != nil {
		return x.SrcIP
	}
	return 0
}

func (x *PacketSummaryMessage) GetSrcMac() uint32 {
	if x != nil {
		return x.SrcMac
	}
	return 0
}

func (x *PacketSummaryMessage) GetDstIP() uint32 {
	if x != nil {
		return x.DstIP
	}
	return 0
}

func (x *PacketSummaryMessage) GetDstMac() uint32 {
	if x != nil {
		return x.DstMac
	}
	return 0
}

func (x *PacketSummaryMessage) GetTTL() uint32 {
	if x != nil {
		return x.TTL
	}
	return 0
}

// Request to Register a New Capturepoint
type RegisterCapturePoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectorID    string `protobuf:"bytes,1,opt,name=CollectorID,proto3" json:"CollectorID,omitempty"`        // Unique Identifier for Source Collector
	Netaddr        uint32 `protobuf:"varint,2,opt,name=Netaddr,proto3" json:"Netaddr,omitempty"`               // Network Address of the local subnet for this capturepoint
	Netmask        uint32 `protobuf:"varint,3,opt,name=Netmask,proto3" json:"Netmask,omitempty"`               // Netmask Mask of the local subnet for this capturepoint
	NicName        string `protobuf:"bytes,4,opt,name=NicName,proto3" json:"NicName,omitempty"`                // system name for NIC of capturepoint - used for reporting
	DefaultGateway uint32 `protobuf:"varint,5,opt,name=DefaultGateway,proto3" json:"DefaultGateway,omitempty"` // MAC address of the default upstream gateway for this subnet
}

func (x *RegisterCapturePoint) Reset() {
	*x = RegisterCapturePoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_packetsummary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCapturePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCapturePoint) ProtoMessage() {}

func (x *RegisterCapturePoint) ProtoReflect() protoreflect.Message {
	mi := &file_packets_packetsummary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCapturePoint.ProtoReflect.Descriptor instead.
func (*RegisterCapturePoint) Descriptor() ([]byte, []int) {
	return file_packets_packetsummary_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterCapturePoint) GetCollectorID() string {
	if x != nil {
		return x.CollectorID
	}
	return ""
}

func (x *RegisterCapturePoint) GetNetaddr() uint32 {
	if x != nil {
		return x.Netaddr
	}
	return 0
}

func (x *RegisterCapturePoint) GetNetmask() uint32 {
	if x != nil {
		return x.Netmask
	}
	return 0
}

func (x *RegisterCapturePoint) GetNicName() string {
	if x != nil {
		return x.NicName
	}
	return ""
}

func (x *RegisterCapturePoint) GetDefaultGateway() uint32 {
	if x != nil {
		return x.DefaultGateway
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaptureID uint32 `protobuf:"varint,1,opt,name=CaptureID,proto3" json:"CaptureID,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_packetsummary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_packetsummary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_packets_packetsummary_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetCaptureID() uint32 {
	if x != nil {
		return x.CaptureID
	}
	return 0
}

type IngestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_packetsummary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_packetsummary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_packets_packetsummary_proto_rawDescGZIP(), []int{3}
}

var File_packets_packetsummary_proto protoreflect.FileDescriptor

var file_packets_packetsummary_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01,
	0x0a, 0x14, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x61, 0x70, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x72, 0x63, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x72, 0x63,
	0x49, 0x50, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x72, 0x63, 0x4d, 0x61, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x53, 0x72, 0x63, 0x4d, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x73,
	0x74, 0x49, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x44, 0x73, 0x74, 0x49, 0x50,
	0x12, 0x16, 0x0a, 0x06, 0x44, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x44, 0x73, 0x74, 0x4d, 0x61, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x54, 0x4c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x54, 0x54, 0x4c, 0x22, 0xae, 0x01, 0x0a, 0x14, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x61, 0x64, 0x64, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x4e, 0x65, 0x74, 0x6d, 0x61, 0x73, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x69, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4e, 0x69, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x30, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x49, 0x44, 0x22, 0x10, 0x0a,
	0x0e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x84, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x06, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x12, 0x15,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3a, 0x0a, 0x0c, 0x43, 0x61,
	0x70, 0x74, 0x75, 0x72, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x1a, 0x11, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x67,
	0x6f, 0x61, 0x74, 0x68, 0x65, 0x72, 0x64, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packets_packetsummary_proto_rawDescOnce sync.Once
	file_packets_packetsummary_proto_rawDescData = file_packets_packetsummary_proto_rawDesc
)

func file_packets_packetsummary_proto_rawDescGZIP() []byte {
	file_packets_packetsummary_proto_rawDescOnce.Do(func() {
		file_packets_packetsummary_proto_rawDescData = protoimpl.X.CompressGZIP(file_packets_packetsummary_proto_rawDescData)
	})
	return file_packets_packetsummary_proto_rawDescData
}

var file_packets_packetsummary_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_packets_packetsummary_proto_goTypes = []interface{}{
	(*PacketSummaryMessage)(nil), // 0: PacketSummaryMessage
	(*RegisterCapturePoint)(nil), // 1: RegisterCapturePoint
	(*RegisterResponse)(nil),     // 2: RegisterResponse
	(*IngestResponse)(nil),       // 3: IngestResponse
}
var file_packets_packetsummary_proto_depIdxs = []int32{
	0, // 0: PacketCollection.Ingest:input_type -> PacketSummaryMessage
	1, // 1: PacketCollection.CapturePoint:input_type -> RegisterCapturePoint
	3, // 2: PacketCollection.Ingest:output_type -> IngestResponse
	2, // 3: PacketCollection.CapturePoint:output_type -> RegisterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packets_packetsummary_proto_init() }
func file_packets_packetsummary_proto_init() {
	if File_packets_packetsummary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packets_packetsummary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketSummaryMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_packetsummary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCapturePoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_packetsummary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_packetsummary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IngestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packets_packetsummary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packets_packetsummary_proto_goTypes,
		DependencyIndexes: file_packets_packetsummary_proto_depIdxs,
		MessageInfos:      file_packets_packetsummary_proto_msgTypes,
	}.Build()
	File_packets_packetsummary_proto = out.File
	file_packets_packetsummary_proto_rawDesc = nil
	file_packets_packetsummary_proto_goTypes = nil
	file_packets_packetsummary_proto_depIdxs = nil
}
